### ISSUE TITLE
<br /> disappear when editing HTML

### ISSUE THREAD

**Issue by haemi** [stevengharris/MarkupEditor#111]
I'm on the main branch and when I load an HTML like e.g.

```
Hello<br />World<br />!!
```

then select "World" and make it bold, all the line breaks are gone; how can I prevent this?

**Comment by stevengharris** [comment]
The MarkupEditor uses a kind of restricted set of HTML. This is, of course, not documented - sorry - except deep in the README where it says:

> "The MarkupEditor has the advantage of not supporting arbitrary HTML, and in fact, owns the definition of the exact subset of HTML that is allowed. It is targeted only at WKWebView, so there are no browser portability problems. The restrictions on functionality and the absence of styling elements from the HTML help avoid some of the problems cited in [his article](https://medium.engineering/why-contenteditable-is-terrible-122d8a40e480). Also, by avoiding use of (the now deprecated but likely to live forever) [Document.execCommand](https://developer.mozilla.org/en-US/docs/Web/API/Document/execCommand) to perform editing tasks against the DOM, the MarkupEditor avoids WebKit polluting the "clean" HTML with spans and styles."

The short answer to this question is to use `<p>Hello</p><p>World</p>!!` and not use the `<br/>`. If you start with a blank document and type "Hello \<Enter> World \<Enter> !!", this is what you will end up with. 

The longer answer is that you can check out [_patchPasteHTML](https://github.com/stevengharris/MarkupEditor/blob/db3bb83ac991fb12606044a54239d7664b14eba7/MarkupEditor/Resources/markup.js#L2183) to understand what is not allowed in arbitrary HTML (random `<br/>` being one). 

```
const _patchPasteHTML = function(html) {
    const template = document.createElement('template');
    template.innerHTML = html;
    const element = template.content;
    _cleanUpSpansWithin(element);
    _cleanUpDivsWithin(element);
    _cleanUpAttributesWithin('style', element);
    _cleanUpAttributesWithin('class', element);
    _cleanUpMetas(element);
    _cleanUpBRs(element);
    _cleanUpNewlines(element);
    _cleanUpPREs(element);
    _cleanUpAliases(element);
    _prepImages(element);
    return element;
};
```

This is the method I use to gate pasting into the MarkupEditor so that it doesn't end up with HTML elements could break its logic at various places or present the document in a way that is not properly editable.

**Comment by haemi** [comment]
but the vertical space between the lines when using `<p>Hello</p><p>World</p>!!` is bigger than with a single `<br />`... it also seems that multiple `<p>&nbsp;</p>` do not lead to multiple empty lines:

```
<p>Hello</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p><b>World</b></p>
```

looks the same as
```
<p>Hello</p>
<p><b>World</b></p>
```

**Comment by stevengharris** [comment]
Yes, on the missing spacing that is a bug, thanks! The `<p>nbsp;></p>` ends up as `<p></p>`, which isn't selectable and doesn't display properly. The "selectable" empty paragraph is `<p><br><p>`, which is what an empty document starts as in the MarkupEditor. 

FWIW, if you want to see the actual raw HTML in the demo, you can modify `DemoContentView.setRawText(_:)` to use `getRawHtml` rather than `getHtml`, which does a kind of homegrown pretty-print:

```
private func setRawText(_ handler: (()->Void)? = nil) {
        MarkupEditor.selectedWebView?.getRawHtml { html in    // <- getRawHtml doesn't do any prettying
            rawText = attributedString(from: html ?? "")
            handler?()
        }
    }
```

It can be handy to paste content into demo.html with this setting to be able to see what's going on at a detailed level.

If you want the spacing between \<p> to be smaller, you will need to adjust the markup.css to fit your case. Currently, for example, this is done for text inside of tables via:

```
table p, table h1, table h2, table h3, table h4, table h5, table h6 {
    margin: 0;
}
```
