### ISSUE TITLE
Not able to limit the number of characters in the editor.

### ISSUE THREAD

**Issue by Palanichamy1986** [stevengharris/MarkupEditor#206]
Not able to limit the number of characters in the editor. Please provide me the solution as soon as possible. Thanks in advance.

**Comment by stevengharris** [comment]
It's going to be difficult to physically limit the characters allowed in the editor. It would involve modifying the function in `MU.editor.addEventListener('keydown'...` so that you can do `ev.preventDefault()` after determining whether the character count is > some value you have previous passed in and saved in state somewhere. In general, I'm trying not to do anything on the JavaScript side when the user is typing, other than for exceptional cases like Enter and Delete and navigation.

An alternative is to use `MarkupDelegate.markupInput` on the Swift side to determine if the character count exceeds your limit, and then just let the use know they've exceeded the limit. It's still a heavyweight thing to do on every keystroke, but may be okay in your case. If you look at the SwiftUIDemo, `DemoContentView.markupInput(_:)` would look like this:

```
func markupInput(_ view: MarkupWKWebView) {
    // This is way too heavyweight, but it suits the purposes of the demo
    setRawText()
    view.getCharCount() { count in
        print("Characters: \(count)")
    }
}
```

You would add a new `getCharCount` function in MarkupWKWebView like this:

```
public func getCharCount(_ handler: ((Int)->Void)?) {
    evaluateJavaScript("MU.getCharCount()") { result, error in
        if let error {
            Logger.webview.error("Error: \(error)")
        } else if let count = result as? Int {
            handler?(count)
        } else {
            Logger.webview.error("Error: charCount result is not an Int")
        }
    }
}
```

And a new function in `markup.js` like this:

```
MU.getCharCount = function() {
    return MU.editor.textContent.length;
};
```

**Comment by stevengharris** [comment]
Feel free to reopen with more info if my suggested approach is insufficient.
