### ISSUE TITLE
Support for Span Style Tag for inline styling

### ISSUE THREAD

**Issue by JohnKuan** [stevengharris/MarkupEditor#27]
Hi @stevengharris, I was testing around the addition of span tag, alongside H1-H6, it seems possible to include in the StyleContext.swift file, but it also will need support on the markup.js file. 

https://www.w3schools.com/tags/tag_span.asp

Since H1-H6 are block level styling, I'm wondering whether will you consider inline styling using span in the future?

I am looking at the possibility to define `<span style="font-size: 23px";>Example</span>` syntax for a user who wants to have finer control on the styling.

**Comment by JohnKuan** [comment]
I just saw a couple of function statements to clean up spans and it is quite often. I'm guessing that there will be resistance to supporting span tags?

**Comment by stevengharris** [comment]
It seems like a natural way to approach the problem, but I don't think it will work without a lot of effort. The first reason I started to "clean up" spans was because the default behavior on Delete and Backspace inserts them into the HTML, presumably as a way to preserve styling. But when that happens, then the styling I'm using gets overridden, and there is no obvious way to make styling changes to behave like expected after that. Similarly, when pasting HTML, you receive all kinds of spans and styling in the contents, which again, if embedded into the receiving HTML leaves it in a condition that is problematic for later editing. I am doing special handling of Enter and Backspace in various places (particularly lists but also surrounding the new ResizableImage), and I would guess a lot of that can be broken with the introduction of spans, as would the undo and redo operations. A lot of the assumptions and limitations here have been shaped by my original scope choice of being like Markdown in scope. Still, I admit, it would be nice if someone with the desire could extend it to handle more complex cases. Maybe at some point it would be possible to inject them like `<span class="StyledText" fontsize="23" color="blue">Example</span>` and then update the "clean up" logic I have in place to leave them in place. I still think a lot of the special event handling and undo/redo logic would require updating to handle it tho.

FWIW, the new ResizableImages (on main) are done by injecting spans around an <img> to show a dashed border and resizing handles, and then attaching event handlers to them. These spans are a visual indicator that the image is selected, but I remove them when returning the HTML for the document. Otherwise, if they came back in as part of a saved document, then they are visible and it looks to the user like the image is selected, but in fact, the actual document.getSelection is elsewhere.

**Comment by stevengharris** [comment]
I don't think I am going to work on this, but I was thinking about an approach that would work, which I wanted to capture here.

- Insert spans with a class identifier, like \<span class="styledtext">\</span> that can then be used to identify them and which might make it easier to capture state and behavior needed similar to ResizableImage.
- Allow spans to include text and other "format" elements like \<b>, \<i>, etc, but they would need to be part of some existing top-level element.
- Add whatever attributes you want to individual spans to style text independently of the top-level block element they're embedded in.
- Do special handling on Enter and Delete (starting with the 'keydown' event on MU.editor and a new method like _doEnter() but for spans - call it _doSpanEnter to be consistent with doListEnter and doBlockquoteEnter that exist now.
- Implement corresponding undo/redo methods.
- Modify _cleanUpSpans to leave the spans with class="styledtext".
- Add something to SelectionState to indicate selection is within a styledTextSpan.
- Implement a new button in the StyleToolbar and a corresponding SubToolbar to allow easy setting of attributes like font size, perhaps color.
- Make sure none of the existing Basic, Undo, Redo tests regress along the way.
- Add new tests for everything that was added.

It's a pretty big project, probably plenty of gotchas as it uncovers implicit assumptions in existing code.

**Comment by JohnKuan** [comment]
Hi @stevengharris, thanks for the thorough explanation on your take for this.

I might have to implement this behaviour down the road, so if it comes to that, I can look out for these pointers you have laid out here. 

Thanks!
