### ISSUE TITLE
Multiple nested indent on UL/OL

### ISSUE THREAD

**Issue by JohnKuan** [stevengharris/MarkupEditor#34]
Hi Steve,

I am looking into the behaviour of the indentation for the ordered and unordered list.

This does not work or constructible.
<ul>
  <ul>
    <ul>
      <ul>
        <li>
          <p>H</p>
        </li>
      </ul>
    </ul>
  </ul>
</ul>

where as this the current behaviour
<ol>
  <li>
    <p>Here is a numbered sublist.</p>
    <ol>
      <li>
        <p>With two items.</p>
      </li>
      <li>
        <p>I</p>
      </li>
    </ol>
  </li>
</ol>

The second item can be indented and that becomes the first item on the newer indent level.

I went through the code and this line in the function _indentListItem
`if (!previousListItem || (previousListItem.nodeName !== 'LI')) { return null };`
returns null because the previous item is null when I tried to indent on the first item.

I have seen this comment that explains the reason to not indent.
// If previousElementSibling doesn't exist or is not
 // an LI, then the indent is not allowed.

Is this logic intentional that we are not able to do multiple indent on the list for the first item on the indent level?

**Comment by JohnKuan** [comment]
The blockquotes seems to be working for doubly nested indentation, as stated in your example html text

<blockquote>
  <blockquote>
    <h5>Here is an example of a header that has been indented twice.</h5>
  </blockquote>
</blockquote>

**Comment by stevengharris** [comment]
It was definitely intentional. I did it this way because according to the HTML standard, [ul](https://html.spec.whatwg.org/multipage/grouping-content.html#the-ul-element) and [ol](https://html.spec.whatwg.org/multipage/grouping-content.html#the-ol-element) are only supposed to contain 1 or more li elements. AFAICT, nesting ul/ol is handled in the spirit of "be liberal about what you allow", not because the spec allows it. 

I am pretty sure I ended up with the restriction because if you take a nested ul example like yours:

<ul>
  <ul>
        <li>
          <p>H</p>
        </li>
      </ul>
</ul>

and put a list item in it such that it holds the ul (you will have to look at the html behind this comment), it ends up messed up:

<ul>
  <li>
    <ul>
        <li>
          <p>H</p>
        </li>
      </ul>
  </li>
</ul>

IIRC, I think I ended up with lists in this kind of state when dealing with outdenting items in lists, which in turn led me to imposing the rule. 

FWIW, there is no similar restriction on blockquotes in the spec. On a related note, I recently reworked the indent/blockquote because I was creating them like this (again, you have to peek at the HTML behind this comment):

<blockquote>
  <p>First level indent</p>
  <blockquote>
    <p>Second level indent line 1</p>
    <p>Second level indent line 2<p>
  </blockquote>
</blockquote>

Since I am using blockquotes for indexing and not using a CSS style to show that the two second level indents are inside the same blockquote (and in fact don't want my user to think about such weird details), it's surprising to find that outdenting the \<p>Second level indent line 2\<p>  outdents both lines because it translates under the covers to "remove the surrounding blockquote". To fix this problem, I now produce blockquotes around the individual \<p> elements, so it looks like this:

<blockquote>
  <p>First level indent</p>
  <blockquote>
    <p>Second level indent line 1</p>
  </blockquote>
  <blockquote>
    <p>Second level indent line 2<p>
  </blockquote>
</blockquote>

That looks bad here on GitHub because of their CSS, but with the MarkupEditor CSS, they just look like indented paragraphs that can now be outdented individually.

**Comment by JohnKuan** [comment]
Hi Steve, thanks for clarifying on this.

As a developer, I am also leaning to your approach for following the HTML standard for the use of UL and OL, since it will have a consistent structure across other html readers. 

I went through on your blockquotes in the example, and I can see that structure that you have mentioned. 

So for now, if a user (for whatever reason) wants to purposefully shift the starting point of the OL/UL, it would be through the blockquotes and then the OL/UL tag in it.
