### ISSUE TITLE
Using Swift UI inside UIKitDemo.

### ISSUE THREAD

**Issue by fadizant** [stevengharris/MarkupEditor#5]
I wonder why did you use SwiftUI inside UIKitDemo. I can't use this great control in my project that supports iOS 11+.

**Comment by stevengharris** [comment]
Hi Fadi. It's a good question! I even built the MarkupEditor to use within another UIKit project originally. I wanted to use it as a way to learn SwiftUI. I also wanted to create a single tool codebase, without maintaining separate SwiftUI and UIKIt UI. I wasn't concerned about compatibility for apps prior to iOS 14, and the project I'm consuming it in will be released on Mac Catalyst and iOS 15. At this point, I have converted the consuming project into SwiftUI almost completely. 

FWIW, part of my learning experience was that while SwiftUI is quite nice in terms of consuming UIKIt componentry, I can't say the same about the reverse. For example, it was easy to use UITextView within the ImageToolbar when SwiftUI's TextView was deficient. However, SwiftUI animations don't play well with some of the UIKit animations when embedding the MarkupToolbar in a UIKit app. I'm sure there must be other issues as well in more of a real-world UIKit app than the SwiftUIDemo. It would probably just make more sense to have a completely UIKit-based alternative set of components for the toolbar rather than try to embed the SwiftUI MarkupToolbar, but I didn't want to have to support multiple codebases for it, especially when my target was a SwiftUI-based app.

The SwiftUI dependencies should all be strictly separated from everything except the MarkupToolbar and its associated classes. For example (except for my importing SwiftUI by mistake in earlier versions), the MarkupEditorTests have no SwiftUI dependency. It should be pretty easy to create a UIKit-based toolbar using UIButtons that invoke the WKMarkupWebView functionality directly. If you did that and folded it into something like a PureUIKitDemo, I would include it in the project. It might also uncover some things that should be refactored.

**Comment by stevengharris** [comment]
No plans to change this state of affairs myself.
