### ISSUE TITLE
SimplestContentView not working on iOS

### ISSUE THREAD

**Issue by cph101** [stevengharris/MarkupEditor#58]
assertionFailure is thrown: “Could not find markup.html, css, and js for this bundle.”

**Comment by stevengharris** [comment]
The markup.html, markup.css, and markup.js are basically the bootstrap resources that install with the MarkupEditor when you include it in your app. Since you didn't provide any information to chase the problem down, I did the following:

1. Created a new SwiftUI app in Version 14.0.1 (14A400)
2. Added the MarkupEditor package (version 0.5.1)
3. Edited the ContentView to:

```
import SwiftUI
import MarkupEditor

struct ContentView: View {
    @State private var demoHtml: String = "<h1>Hello World</h1>"
    
    var body: some View {
        MarkupEditorView(html: $demoHtml)
    }
}
```

4. Launched the app to deploy to the iPhone 14 Pro simulator running iOS 16.0.

It comes up showing "Hello World" and does not show the assertion failure.

I am not sure what situation would prevent the bootstrap file resources from being found. When I was sorting the initialization sequence out a long time ago, I would step thru `initRootFiles()` in MarkupWKWebView (where the assertion is made) to try to understand how `bundle()` and the `bundle.url(forResource name: [String])` were behaving. Maybe my assumptions on how to locate the bundle are somehow incorrect in your environment, in which case, please let me know so I can handle your case properly. At least it would be good to make sure (if that's not where you started) that a completely new app started from scratch like I described above works.

**Comment by cph101** [comment]
Thanks a lot,

I will see if these steps work. Thanks again,

cph101
