### ISSUE TITLE
Binding property in SwiftUI not working

### ISSUE THREAD

**Issue by YanVetrov** [stevengharris/MarkupEditor#81]
```
@State var value = "sample"      

MarkupEditorView(html:$value)   

```
No errors the editor works, but any changes do not affect the "value" property, in this example it is always "sample". The demo in the repository is the same.
ios 16.1 simulator and device

**Comment by mrzky** [comment]
same issue here on iphone se 2020 iOS 16.3

**Comment by stevengharris** [comment]
The interaction with the MarkupWKWebView is all async, so you have to hook into the MarkupDelegate.markupInput method to know on the Swift side when input occurs (like the demo does) or on calling getHtml yourself. It doesn't get reflected back into the original value passed in the binding. In my own usage on a larger doc, I key off of markupInput to track that the document changed, but I have a kind of auto-save logic to getHtml and save it on a less frequent basis than each keystroke. The demo (it's a demo!) gets the html at each keystroke so as to update the raw html that can be displayed below the document.

**Comment by mrzky** [comment]
oh my bad, thank you

**Comment by stevengharris** [comment]
FWIW, since two people were caught by this, it seems like more of a problem of missing documentation.  It seems like the obvious thing for something like a text editor to do on some bound text passed into it. Admittedly, it's not obvious that a binding to the html doesn't just update - after all, why use a binding in the first place? I used the binding because I wanted to be able to reset the html contents in the MarkupEditor, which is something I do in the demo from the FileToolbar and seems generally useful. Anyway, thanks for raising the issue.
