### ISSUE TITLE
Auto style text with markdown

### ISSUE THREAD

**Issue by Erik-Handeland** [stevengharris/MarkupEditor#82]
I'm trying to implement auto formatting markdown syntax similar to Typora. i.e convert `**Bold Text**` to `<b>Bold Text</b>` on the fly without needing the tool bar. I managed to get the replacement to work by adding a regex function to markup.js function `const _doEnter` which triggers when returning to a new line. But using the demo project I can't get my changes to render:
<img src="https://user-images.githubusercontent.com/16601367/210189216-6ed36bf6-ef17-45b8-bb04-ee0c96230cc2.gif" width="500">

I'm sure this isn't the best way to implement this so I'd love some suggestions on how to implement this

```javascript
function parseMarkdown(markdownText) {
    const htmlText = markdownText
    .replace(/^### (.*$)/gim, '<h3>$1</h3>')
    .replace(/^## (.*$)/gim, '<h2>$1</h2>')
    .replace(/^# (.*$)/gim, '<h1>$1</h1>')
    .replace(/^\> (.*$)/gim, '<blockquote>$1</blockquote>')
    .replace(/\*\*(.*)\*\*/gim, '<b>$1</b>')
    .replace(/\*(.*)\*/gim, '<i>$1</i>')
    .replace(/!\[(.*?)\]\((.*?)\)/gim, "<img alt='$1' src='$2' />")
    .replace(/\[(.*?)\]\((.*?)\)/gim, "<a href='$2'>$1</a>")
    .replace(/\n$/gim, '<br />')
    
    return htmlText.trim()
}

/**
 * Handle the Enter key to avoid <div> being inserted instead of <p>
 *
 * @returns {HTML Paragraph Element || null}    The newly created P to preventDefault handling; else, null.
 */
const _doEnter = function(undoable=true) {
    let sel = document.getSelection();
     ...
    const parent = _findFirstParentElementInNodeNames(selNode, _paragraphStyleTags);
    
    _consoleLog(selNode.textContent)
    selNode.textContent = parseMarkdown(selNode.textContent) // *** Parse markdown from line selection 
    _consoleLog(selNode.textContent)
    
    if (selectionAtEnd && nextSiblingIsEmpty && parent) {
       ...
    };
    return null;    // Let the MarkupWKWebView do its normal thing
};
```

**Comment by stevengharris** [comment]
I am not sure if it's the root of your problem, but `_doEnter` never gets called when running on a Mac running on Ventura because of https://github.com/stevengharris/MarkupEditor/issues/76. As documented in that issue, I've submitted a Feedback item on the problem, and I've tried to find some kind of workaround, but AFAICT the problem is hidden inside of some Catalyst layer. I feel very stuck on the issue and will get pushed into doing a real Mac version as a workaround for my own purposes if it just ends up in some Apple black hole. 

If that's not the problem, maybe you are not doing the `_callback('input');` and `return p;`? The `_callback('input');` triggers the update of the raw HTML in the demo, and the `return p;` makes sure `preventDefault()` happens for the `input` event, which might be wiping out what you did.

On the general topic of how to implement what you're doing, I'm not sure I have any good suggestions. In my experimentation with round-tripping between the MarkupEditor "basic HTML" and Markdown, I tried both [turndown](https://github.com/mixmark-io/turndown) and [showdown](https://github.com/showdownjs/showdown). These are both pretty easy to fold in as libraries using the `userScripts` parameter when creating the view. Maybe this is too heavyweight for your use case, but if you want to try them and have any issues or questions about how to deal with `userScripts` and making them work, let me know and I can either post the round-trip demo or answer any questions.

**Comment by Erik-Handeland** [comment]
Hmm, I wasn't having any issues with `_doEnter` not being called. I'm able to add a print message `_consoleLog("Enter Key Pressed")` and see it. I'm running a similar setup macOS 13.1, although I'm using an M1 Mac and Xcode 14.2

🤦‍♂️ I haven't done web development in a while so when I was looking to get the text and just grabbed the first member function that looked right `selNode.textContent = parseMarkdown(selNode.textContent)`. However changing that does not alter the underlining HTML. So `parent.innerHTM` which was being rendered was still showing the escaped html... Should have done `parent.innerHTML = parseMarkdown(selNode.textContent)`.  Such a dumb mistake, wish Xcode allowed for breakpoints in JS.

Thanks for the suggestion, Those libraries will be helpful

**Comment by Erik-Handeland** [comment]
Showdown and userscripts worked out great, thanks again for the tip

![Kapture 2023-01-03 at 00 27 08](https://user-images.githubusercontent.com/16601367/210330785-a49c2e0a-795a-47f3-94df-5b4850c4c9ee.gif)

**Comment by stevengharris** [comment]
It was a great day when I finally discovered that with your app open (e.g., the SwiftUIDemo), you can open the WebInspector from the Develop menu in Safari and then set breakpoints, step thru, and examine variables.

**Comment by bastiaanterhorst** [comment]
@Erik-Handeland I'm looking to do precisely what you have built here. Would you be willing to share your working code?
